config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get 'user/:username', to: 'user#show', as: 'user'

  get '/user/:username/avatar', to: 'user#edit_avatar', as: 'avatar'

  delete 'user/:username', to: 'user#destroy'

  patch '/user/:username/avatar', to: 'user#update_avatar'

  get '/users/:query', to: 'user#search_user'

  get '/find', to: 'user#find', as: 'find'

  # admin

  get 'admin', to: 'admin#show', as: 'admin'

  get 'admin/new_user', to: 'admin#new_user', as: 'admin_new_user'

  post 'admin/create_user', to: 'admin#create_user'

  resources :trips

  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :trip

  mount_uploader :image, ImageUploader
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user

  has_many :photos, dependent: :delete_all
end

app/models/user.rb
# user class
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_presence_of :name

  validates_uniqueness_of :username

  has_many :trips, dependent: :delete_all

  enum role: %i[user vip admin]
  after_initialize :set_default_role

  def set_default_role
    self.role ||= :user
  end

  mount_uploader :avatar, AvatarUploader
end

# /etc/init.d/postgresql restart

app/controllers/admin_controller.rb
# contains functionality of admin page
class AdminController < ApplicationController
  before_action :check_admin

  def show
    @users = User.all
  end

  def new_user
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_path
    else

      flash[:error] = []

      flash[:error] << 'email taken' if User.find_by_email(params[:email]).nil?

      flash[:error] << 'username taken' if User.find_by_email(params[:username]).nil?

      flash[:error] << 'password don\'t match' if params[:password] != params[:password_confirmation]

      return redirect_to admin_new_user_path
    end
  end

  def delete_user
    @user = User.find_by_username!(params[:username])

    @user.destroy
    ##  @user.delete

  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :name,
                                 :username,
                                 :password,
                                 :password_confirmation,
                                 :role)
  end

  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :sanitize_devise_parameters, if: :devise_controller?

  def sanitize_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'home/index'
  end
end

app/controllers/photos_controller.rb
# photo of trips
class PhotosController < ApplicationController
  def new
    @photo = Photo.new(trip_id: params[:trip_id])
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = 'Successfully created photo.'
      redirect_to @photo.trip
    else
      render action: 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      flash[:notice] = 'Successfully updated photo.'
      redirect_to @photo.trip
    else
      render action: 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:notice] = 'Successfully destroyed photo.'
    respond_to do |format|
      format.html { redirect_to @photo.trip }
      format.js
    end
  end

  def photo_params
    params.require(:photo).permit(:trip_id,
                                  :image,
                                  :remote_image_url)
  end
end

app/controllers/trips_controller.rb
# users can describe their trips
class TripsController < ApplicationController
  before_action :authenticate_user!

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user

    @trip.save
    redirect_to @trip
  end

  def edit
    @trip = Trip.find(params[:id])

    if @trip.user != current_user
      redirect_to @trip, notice: 'You can\'t change other users trips'
    end
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      redirect_to @trip
    else
      render 'edit'
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    if current_user != @trip.user && !current_user.admin?
      redirect_to @trip
    end

    @trip.destroy
    redirect_to root_path
  end

  private

  def trip_params
    params.require(:trip).permit(:title,
                                 :description,
                                 :h_latitude,
                                 :h_longitude,
                                 :d_latitude,
                                 :d_longitude)
  end
end

# AIzaSyBvGpbaHwB8tCQ2O1uBjNc08r9Z8J7a89Y
# my maps key
# get started with maps
# https://developers.google.com/maps/documentation/javascript/

app/controllers/user_controller.rb
# user functionality
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by_username!(params[:username])
  end

  def edit_avatar
    @user = User.find_by_username!(params[:username])
  end

  def update_avatar
    @user = User.find_by_username!(params[:username])
    if @user.id != current_user.id
      flash[:notice] = 'You don\'t have the right to edit this user avatar'
      redirect_to user_path(@user.username)
    end

    if @user.update_attributes(user_avatar)
      flash[:notice] = 'Successfully updated avatar.'
      redirect_to user_path(@user.username)
    else
      render action: 'edit_avatar'
    end
  end

  def destroy
    @user = User.find_by_username!(params[:username])
    if current_user.admin?
      @user.destroy
      redirect_to admin_path
    end
  end

  def find
    render 'user/search_user'
  end

  def search_user
    # @users = User.where('name LIKE ?', params[:query])
    #              .where('username LIKE ?', params[:query])

    @users = User.where('lower(name) LIKE ? or lower(username) LIKE ?',
                        "%#{params[:query].downcase}%",
                        "%#{params[:query].downcase}%")

    render json: @users.as_json
  end

  def create_user
    render 'create_account'
  end

  private

  def user_avatar
    params.require(:user).permit(:avatar)
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="error_explanation">
    <h2><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/new_user.html.erb
<div class="container admin-body">
  <div class="admin-container newuser-container">

    <%= form_for @user, url: {controller: 'admin', action: 'create_user'} do |f| %>

      <h1>Create account for someone as admin</h1>
      <ul>
        <% unless flash[:error].nil?
             flash[:error].each do |item| %>
            <li><%= item %></li>
          <% end %>
        <% end %>
      </ul>
      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :username %><br/>
        <%= f.text_field :username, autofocus: true, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br/>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :role %><br/>
        <select name="user[role]" id="user_role" class="form-control">
          <option value="user">User</option>
          <option value="vip">Vip</option>
          <option value="admin">Admin</option>
        </select>
      </div>

      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/show.html.erb
<div class="container admin-container">
  <table>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Administration</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <th><%= user.username %></th>
        <th><%= user.name %></th>
        <th><%= user.email %></th>
        <th><%= user.role %></th>
        <th><%= link_to 'Delete', user_path(user.username), controller: :user, method: :delete, data: {confirm: 'Are you sure you want to delete this user?'} %></th>
      </tr>
    <% end %>
    <tr>
      <th colspan="5"><%= link_to 'Add new user', admin_new_user_path%></th>
    </tr>
  </table>
</div>

app/views/home/index.html.erb
<div class="welcome_message ">
  <div class="title uk-text-primary uk-animation-slide-bottom">
    <h1>Welcome to places</h1>
    <span class="text-gradient"></span>
  </div>
  <p>
    Travel, Share your experience and discover new places.
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvGpbaHwB8tCQ2O1uBjNc08r9Z8J7a89Y&callback=initMap"
          async defer></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default my-nav">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand" href="#"><%= link_to 'Places', root_path, class: 'navbar_link', id: 'title_navbar' %></div>
    </div>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-left">
        <li>
          <div class="input">
            <input type="text" class="form-control" id="search" placeholder="look for someone">
          </div>
          <ul id="result">

          </ul>
        </li>
      </ul>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a>You are logged as <%= current_user.role %></a></li>
        <li><%= link_to 'Post a new trip', new_trip_path %></li>
        <li>
          <div class="dropdown">
            <button type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Account settings
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to current_user.name, user_path(current_user.username), id: "current_user_link", class: "current_user_link" %></li>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin Page', admin_path %></li>
              <% end %>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <%= f.hidden_field :trip_id %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/photos/destroy.js.erb
$('#photo_<%= @photo.id %>').remove();

app/views/photos/edit.html.erb
<h1>Edit photo</h1>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @photo.trip %></p>

app/views/photos/new.html.erb
<h1>New Painting</h1>

<%= render 'form' %>

<p><%= link_to "Back to Gallery", @photo.trip %></p>

app/views/trips/edit.html.erb
<div class="form_big_container">
  <div class="form_container">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <h1>New Trip</h1>

    <%= form_for @trip do |form| %>
      <div class="input_container">
        <div><%= form.label :title %></div>
        <div><%= form.text_field :title %></div>
      </div>

      <div class="input_container">
        <div><%= form.label :description, 'Tell us how it was!!!' %></div>
        <div><%= form.text_area :description %></div>
      </div>


      <div class="coordinates_container">

        <div class="coordinate_container">
          <h3>Home coordinates</h3>
          <div class="input_container">
            <div><%= form.label :h_latitude, 'Latitude' %></div>
            <div><%= form.number_field :h_latitude %></div>
          </div>

          <div class="input_container">
            <div><%= form.label :h_longitude %></div>
            <div><%= form.number_field :h_longitude %></div>
          </div>
        </div>

        <div class="coordinate_container">
          <h3>Destination coordinates</h3>
          <div class="input_container">
            <div><%= form.label :d_latitude, 'Latitude' %></div>
            <div><%= form.number_field :d_latitude %></div>
          </div>

          <div class="input_container">
            <div><%= form.label :d_longitude %></div>
            <div><%= form.number_field :d_longitude %></div>
          </div>
        </div>
      </div>
      <div class="input_container submit_button">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/trips/show.html.erb
<div class="trip_show_container">
  <div class="header">
    <h1><%= @trip.title %></h1>
  </div>
  <div class="body">
    <div class="info">
      <div class="settings_and_info">
        <% if current_user == @trip.user %>
          <%= link_to "Add a photo", new_photo_path(:trip_id => @trip), id: 'add_photo' %>
        <% end %>
      </div>
      <div class="description">
        <input id="h_lat" value="<%= @trip.h_latitude %>" style="display: none">
        <input id="h_lng" value="<%= @trip.h_longitude %>" style="display: none">
        <input id="d_lat" value="<%= @trip.d_latitude %>" style="display: none">
        <input id="d_lng" value="<%= @trip.d_longitude %>" style="display: none">

        <p><%= @trip.description %></p>
      </div>
    </div>
    <div class="map" id="trip_map">

    </div>
  </div>
  <div class="gallery">
    <div class="owl-carousel">
      <% for photo in @trip.photos %>
        <div id="photo_<%= photo.id %>" class="photo">
          <div><a href="<%= photo.image_url.to_s %>" data-lightbox="photo<%= photo.id %>"><%= image_tag photo.image_url.to_s %></a></div>
          <div><%= photo.name %></div>
          <div>
            <% if current_user == photo.trip.user %>
              <%= link_to "edit", edit_photo_path(photo) %>
            <% end %>

            <% if current_user == photo.trip.user || current_user.admin? %>
              <%= link_to "remove", photo, method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/create_account.html.erb
<div class="auth_body_container">
  <div class="auth_container">
    <h2>Sign up</h2>

    <%= form_for @user do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.label :email %><br/>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :username %><br/>
        <%= f.text_field :username, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :role %><br/>
        <%= f.select_tag :role, options_for_select([["admin", 2], ["vip", 1], ["user", 0]]) %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br/>
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>

    <%= render "devise/shared/links" %>
  </div>
</div>

app/views/user/edit_avatar.erb
<div class="auth_body_container">
  <div class="auth_container" style="margin-top: 20px;">
    <%= form_for @user do |f| %>

      <div class="field">
        <%= f.file_field :image %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/edit_avatar.html.erb
<div class="auth_body_container">
  <div class="auth_container" style="margin-top: 20px;">
    <%= form_for @user, url: {action: :update_avatar} do |f| %>

      <div class="field">
        <%= f.file_field :avatar %>
      </div>

      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="container container-profile">
  <div class="my-background"></div>
  <div class="my-card">
    <div class="my-card-header">
      <h4><%= @user.name %></h4>
    </div>
    <div class="my-card-body">
      <div class="avatar">
        <%= image_tag @user.avatar.to_s, class: 'avatar' %>
      </div>
      <div class="profile_info">
        <p>Bucharest Romania</p>
        <p>
          <% if @user == current_user %>
            <%= link_to 'update avatar', avatar_path %>
          <% end %>
          <% if current_user == @user || current_user.admin? %>
            | <%= link_to 'Delete this user', user_path, method: :delete, data: {confirm: 'Are you sure you want to delete this user?'} %>
          <% end %>
        </p>
      </div>
    </div>
  </div>


  <div class="container container-trips">
    <% @user.trips.each do |item| %>
      <div class="container-trip">
        <div class="container-trip-header">
          <h4 class=""><%= link_to item.title, trip_path(item) %></h4>
        </div>
        <div class="container-trip-body">
          <div class="trip-image">
            <% unless item.photos.first.nil? %>
              <%= image_tag item.photos.first.image_url, class: 'trip' %>
            <% end %>
          </div>
          <div class="container-trip-description">
            <p id="trip_description_<%= item.id %>"><%= item.description %></p>
            <script>
                if ($('p#trip_description_<%=item.id%>').text().length > 400) {
                    var a = $('p#trip_description_<%=item.id%>').text().slice(0, 400) + "... read more on the trip";
                    $('p#trip_description_<%=item.id%>').text(a);
                }
            </script>
            <ul class="list-inline list-unstyled">
              <li><span><%= item.created_at %></span></li>
              <% if current_user == item.user %>
                <li><%= link_to 'Edit', edit_trip_path(item) %></li>
              <% end %>
              <% if current_user == item.user || current_user.admin? %>
                <li><%= link_to 'Delete', trip_path(item), method: :delete, data: {confirm: 'Are you sure?'} %></li>
              <% end %>
              <!-- TODO de interesat ondelete cascade-->
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>